set_property SRC_FILE_INFO {cfile:C:/Users/Jason/Dropbox/ULB/MA2/Memoire/Github/VFAT3-Testbench/Firmware/project_ipbus_vivado/project_ipbus_vivado.srcs/constrs_1/imports/ucf/kc705_basex.tcl rfile:../../../project_ipbus_vivado.srcs/constrs_1/imports/ucf/kc705_basex.tcl id:1 unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Jason/Dropbox/ULB/MA2/Memoire/Github/VFAT3-Testbench/Firmware/project_ipbus_vivado/project_ipbus_vivado.srcs/constrs_1/new/pinplan.xdc rfile:../../../project_ipbus_vivado.srcs/constrs_1/new/pinplan.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports {leds[0]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {leds[1]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN AC9 [get_ports {leds[2]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports {leds[3]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN P19 [get_ports {sfp_los}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports eth_rx_p]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports eth_clk_p]
